// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  Address,
  DataSourceTemplate,
  DataSourceContext,
} from "@graphprotocol/graph-ts";

export class AToken extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("AToken", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext("AToken", [address.toHex()], context);
  }
}

export class VariableDebtToken extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("VariableDebtToken", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "VariableDebtToken",
      [address.toHex()],
      context,
    );
  }
}
